version: '3.8'

services:
  nginxservice:
    image: mg52-nginx-server
    build: 
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - mg52-ngnix-bridge
  
  backendservice:
    image: mg52-backend-server
    build:
      context: ./backend
    ports:
        - "8090:8090"
    networks: 
      - mg52-ngnix-bridge

networks:
  mg52-ngnix-bridge: